# Pod on UDN 10.10.10.0/24 (extranet). Cluster advertises this subnet to the bastion so you can reach the pod from the VM.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udn-pod
  namespace: extranet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udn-bastion-pod
  template:
    metadata:
      labels:
        app: udn-bastion-pod
    spec:
      containers:
        - name: app
          image: quay.io/rh_ee_prajendr/ubi-minimal-nettools:latest
          command: ["sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
