# One pod per namespace on the Layer3 CUDN (200.1.x.x). L3 connectivity across namespaces.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: udn-layer3-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-layer3
  template:
    metadata:
      labels:
        app: app-layer3
    spec:
      containers:
        - name: app
          image: quay.io/rh_ee_prajendr/ubi-minimal-nettools:latest
          command: ["sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: udn-layer3-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-layer3
  template:
    metadata:
      labels:
        app: app-layer3
    spec:
      containers:
        - name: app
          image: quay.io/rh_ee_prajendr/ubi-minimal-nettools:latest
          command: ["sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
