# Pod on default network. Service default-svc is reachable only from default-network namespaces.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-app
  template:
    metadata:
      labels:
        app: default-app
    spec:
      containers:
        - name: app
          image: registry.k8s.io/e2e-test-images/agnhost:2.45
          args: ["serve-hostname", "--http-port", "8080", "--udp-port", "-1"]
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
